### ISSUE TITLE
KeyError: 'remotes'

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#111]
on my recent deploy I get this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/attmap/ordattmap.py", line 45, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'remotes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/refgenieserver", line 10, in <module>
    sys.exit(main())
  File "/app/refgenieserver/main.py", line 59, in main
    from .routers import private, version1, version2, version3
  File "/app/refgenieserver/routers/version3.py", line 25, in <module>
    RemoteClassEnum = Enum("RemoteClassEnum", {r: r for r in rgc["remotes"]})
  File "/usr/local/lib/python3.7/site-packages/attmap/pathex_attmap.py", line 56, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/usr/local/lib/python3.7/site-packages/attmap/ordattmap.py", line 47, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/usr/local/lib/python3.7/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: 'remotes'
```

I guess this is because I'm using the dev version of refgenieserver, which is expecting a new config format. But it is not creating it when I archive automatically. maybe it should not require the remotes to be set? Or have the archiver set it?

**Comment by stolarczyk** [comment]
I built some logic to prevent that:

https://github.com/refgenie/refgenieserver/blob/83fcd14beb77cfae2c08f91baf7bdf00cefa75a0/refgenieserver/helpers.py#L140-L200

but it is executed in the endpoints, after the custom `Enum`is created. I missed that...

> maybe it should not require the remotes to be set?

the `remotes` key is not intended to be required. However, it's the only way to set the remote data source now. It superseded `remote_url_base` key since it provides the same functionality, but is more flexible.

> Or have the archiver set it?

`remote_url_base` wasn't being inserted by the archiver, so I didn't implement it for `remotes`.
