### ISSUE TITLE
do not rely in args.config in archiver

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#32]
```
refgenieserver archive
email-validator not installed, email fields will be treated as str.
To install, run: pip install email-validator
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenieserver", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.7/site-packages/refgenieserver/main.py", line 124, in main
    archive(rgc, args)
  File "/home/nsheff/.local/lib/python3.7/site-packages/refgenieserver/server_builder.py", line 26, in archive
    server_rgc_path = os.path.join(rgc[CFG_ARCHIVE_KEY], os.path.basename(args.config))
  File "/home/nsheff/miniconda3/lib/python3.7/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

it should be reading the config from REFGENIE? or at least giving an understandable error.

**Comment by stolarczyk** [comment]
you're right, it should. I'll look into that
