### ISSUE TITLE
Error with archive

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#35]
Separate from #32; if I give the config then I get this error:

```
refgenieserver -c $REFGENIE archive
email-validator not installed, email fields will be treated as str.
To install, run: pip install email-validator
Traceback (most recent call last):
  File "/home/nsheff/miniconda3/lib/python3.7/site-packages/attmap/pathex_attmap.py", line 31, in __getattr__
    v = super(PathExAttMap, self).__getattribute__(item)
AttributeError: 'YacAttMap' object has no attribute 'set_default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nsheff/miniconda3/lib/python3.7/site-packages/attmap/ordattmap.py", line 45, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'set_default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nsheff/miniconda3/lib/python3.7/site-packages/attmap/pathex_attmap.py", line 34, in __getattr__
    return self.__getitem__(item, expand)
  File "/home/nsheff/miniconda3/lib/python3.7/site-packages/attmap/pathex_attmap.py", line 51, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/home/nsheff/miniconda3/lib/python3.7/site-packages/attmap/ordattmap.py", line 47, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/home/nsheff/miniconda3/lib/python3.7/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: 'set_default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenieserver", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.7/site-packages/refgenieserver/main.py", line 124, in main
    archive(rgc, args)
  File "/home/nsheff/.local/lib/python3.7/site-packages/refgenieserver/server_builder.py", line 52, in archive
    asset_desc = rgc[CFG_GENOMES_KEY][genome][CFG_ASSETS_KEY][asset_name].set_default(CFG_ASSET_DESC_KEY, "NA")
  File "/home/nsheff/miniconda3/lib/python3.7/site-packages/attmap/pathex_attmap.py", line 38, in __getattr__
    raise AttributeError(item)
AttributeError: set_default
```

**Comment by stolarczyk** [comment]
`set_default` is a typo (should be `setdefault`) which [was fixed on dev](https://github.com/databio/refgenieserver/commit/40072a1be5d2dc9ea3fc24b76a8434c77cd730b2) some time ago
