### ISSUE TITLE
Archive function also requires a `genomes_desc` argument

### ISSUE THREAD

**Issue by jpsmith5** [databio/refgenieserver#55]
According to readme, the archive function only requires a config file:
"refgenieserver archive -c CONFIG
It just requires a -c argument or $REFGENIE environment variable."

However, it also appears to require `genomes_desc`:

```
refgenieserver archive -c test_multiple_servers.yaml 
Traceback (most recent call last):
  File "/home/user/.local/bin/refgenieserver", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/refgenieserver/main.py", line 32, in main
    archive(rgc, arp, args.force, args.remove, selected_cfg)
TypeError: archive() missing 1 required positional argument: 'genomes_desc'
```

**Comment by jpsmith5** [comment]
Even when including that option it isn't being recognized:
```
$ refgenieserver archive -c test_multiple_servers.yaml --genomes_desc test/genomes_descriptions.csv 
Traceback (most recent call last):
  File "/home/user/.local/bin/refgenieserver", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/refgenieserver/main.py", line 32, in main
    archive(rgc, arp, args.force, args.remove, selected_cfg)
TypeError: archive() missing 1 required positional argument: 'genomes_desc'
```

**Comment by stolarczyk** [comment]
I'm confused, I'm sure I used this functionality to build what's currently served at master. Maybe I fixed these issues locally but did not commit the changes..

this should fix that. Thx for reporting!

**Comment by jpsmith5** [comment]
Okay, getting there...

Now it's waiting for a file lock before timing out.

```
$ refgenieserver archive -c test_multiple_servers.yaml
INFO in archive: creating asset '/home/user/src/test/archive/test/fasta__default.tgz' from '/home/user/src/test/fasta/default'
fasta/
fasta/test.fa.fai
fasta/test.fa
fasta/test.chrom.sizes
Waiting for file lock: /home/user/src/test/archive/lock.test_multiple_servers.yaml ....Traceback (most recent call last):
  File "/home/user/.local/bin/refgenieserver", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/refgenieserver/main.py", line 32, in main
    archive(rgc, arp, args.force, args.remove, selected_cfg, args.genomes_desc)
  File "/home/user/.local/lib/python3.7/site-packages/refgenieserver/server_builder.py", line 147, in archive
    rgc_server = RefGenConf(filepath=server_rgc_path, writable=True)
  File "/home/user/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 73, in __init__
    super(RefGenConf, self).__init__(filepath=filepath, entries=entries, writable=writable, wait_max=wait_max)
  File "/home/user/.local/lib/python3.7/site-packages/yacman/yacman.py", line 84, in __init__
    _make_rw(filepath, wait_max)
  File "/home/user/.local/lib/python3.7/site-packages/yacman/yacman.py", line 265, in _make_rw
    _wait_for_lock(lock_path, wait_max)
  File "/home/user/.local/lib/python3.7/site-packages/yacman/yacman.py", line 227, in _wait_for_lock
    raise RuntimeError("The maximum wait time has been reached and the lock file still exists.")
RuntimeError: The maximum wait time has been reached and the lock file still exists.

```

**Comment by stolarczyk** [comment]
Did you try to remove the lock and run archiver again? Maybe it's just a lock that's left by a previous failed process

**Comment by jpsmith5** [comment]
Yeah that was first thing. Removed all contents from the genome_archive directory.

**Comment by jpsmith5** [comment]
Config file:
```
config_version: 0.3
genome_folder: /home/user/src
genome_server: http://refgenomes.databio.org
genome_archive: /home/user/src/test/archive
genomes:
  test:
    assets:
      fasta:
        asset_description: Sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: test.fa
              fai: test.fa.fai
              chrom_sizes: test.chrom.sizes
            asset_digest: e18c0446f55f2584bf58f04076400ce6
            asset_parents: []
        default_tag: default
    genome_digest: c4524d729c745246cd2a47476b46922ce359e9a16fcdae6b
    genome_description: A small test file for multiple server testing
```

Debug output:
```
$ refgenieserver archive -c test_multiple_servers.yaml -d
DEBUG in init_logger: Configured logger 'refgenieserver' using logmuse v0.2.4
DEBUG in archive: registry_paths: []
DEBUG in archive: Genomes to be processed: ['test']
DEBUG in archive: updating 'test' genome attributes...
DEBUG in archive: Assets to be processed: ['fasta']
DEBUG in archive: updating 'test/fasta' asset attributes...
INFO in archive: creating asset '/home/user/src/test/archive/test/fasta__default.tgz' from '/home/user/src/test/fasta/default'
DEBUG in _check_tgz: command: cd /home/user/src/test/fasta/default; mkdir fasta; mv `find . -type f -not -path './_refgenie_build*'` fasta  2>/dev/null; tar -cvf - fasta | pigz > /home/user/src/test/archive/test/fasta__default.tgz; mv fasta/* .; rm -r fasta
fasta/
fasta/test.fa.fai
fasta/test.fa
fasta/test.chrom.sizes
DEBUG in _copy_recipe: Recipe copied to: /home/user/src/test/archive/test
DEBUG in _copy_log: Log copied to: /home/user/src/test/archive/test
Waiting for file lock: /home/user/src/test/archive/lock.test_multiple_servers.yaml ....Traceback (most recent call last):
  File "/home/user/.local/bin/refgenieserver", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/refgenieserver/main.py", line 32, in main
    archive(rgc, arp, args.force, args.remove, selected_cfg, args.genomes_desc)
  File "/home/user/.local/lib/python3.7/site-packages/refgenieserver/server_builder.py", line 147, in archive
    rgc_server = RefGenConf(filepath=server_rgc_path, writable=True)
  File "/home/user/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 73, in __init__
    super(RefGenConf, self).__init__(filepath=filepath, entries=entries, writable=writable, wait_max=wait_max)
  File "/home/user/.local/lib/python3.7/site-packages/yacman/yacman.py", line 84, in __init__
    _make_rw(filepath, wait_max)
  File "/home/user/.local/lib/python3.7/site-packages/yacman/yacman.py", line 265, in _make_rw
    _wait_for_lock(lock_path, wait_max)
  File "/home/user/.local/lib/python3.7/site-packages/yacman/yacman.py", line 227, in _wait_for_lock
    raise RuntimeError("The maximum wait time has been reached and the lock file still exists.")
RuntimeError: The maximum wait time has been reached and the lock file still exists.
```

**Comment by jpsmith5** [comment]
Following up here: removing the archive directory itself, prior to running `archive` resolves the lock file error.
