### ISSUE TITLE
KeyError: 'tags'

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#85]
Related to #84 
```
refgenieserver archive dm6/fasta --config /project/shefflab//deploy/rg.databio.org/refgenomes.databio.org/config/refgenie_config.yaml --dbg
DEBUG in init_logger: Configured logger 'refgenieserver' using logmuse v0.2.6
DEBUG in archive: Registry_paths: [{'protocol': None, 'namespace': 'dm6', 'item': 'fasta', 'subitem': None, 'tag': None}]
DEBUG in archive: Genomes to be processed: ['dm6']
DEBUG in archive: Updating 'dm6' genome attributes...
DEBUG in archive: Assets to be processed: fasta
DEBUG in archive: Updating 'dm6/fasta' asset attributes...
DEBUG in archive: '/project/shefflab//deploy/rg.databio.org/genomes/archive/dm6/fasta__default.tgz' exists
Traceback (most recent call last):
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/ordattmap.py", line 45, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenieserver/server_builder.py", line 274, in _purge_nonservable
    for tag_name, tag in list(asset[CFG_ASSET_TAGS_KEY].items()):
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/pathex_attmap.py", line 51, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/ordattmap.py", line 47, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: 'tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/ordattmap.py", line 45, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/refgenieserver", line 10, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenieserver/main.py", line 41, in main
    archive(rgc, arp, args.force, args.remove, selected_cfg, args.genomes_desc)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenieserver/server_builder.py", line 196, in archive
    _purge_nonservable(r)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenieserver/server_builder.py", line 279, in _purge_nonservable
    rgc.cfg_remove_assets(genome_name, asset_name)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 994, in cfg_remove_assets
    self.remove_asset_from_relatives(genome, asset, tag)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 773, in remove_asset_from_relatives
    tag_data = self[CFG_GENOMES_KEY][genome][CFG_ASSETS_KEY][asset][CFG_ASSET_TAGS_KEY][tag]
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/pathex_attmap.py", line 51, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/ordattmap.py", line 47, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: 'tags'
```

**Comment by nsheff** [comment]
I believe this was just a manifestation of https://github.com/databio/yacman/issues/34 and things were failing before it got to here...

**Comment by nsheff** [comment]
this turned out to *not* be the same as the yacman error, I guess.

**Comment by stolarczyk** [comment]
yes, the wait time was a different problem.
